# Generated by Django 3.1 on 2020-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200826_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_info',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='info_text',
            field=models.CharField(max_length=500),
        ),
    ]
